openapi: 3.0.1
info:
  title: Backend Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9595"
paths:
  /{fhirType}:
    get:
      operationId: getFhirtype
      parameters:
      - name: fhirType
        in: path
        required: true
        schema:
          type: string
      - name: searchParams
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components: {}
