[package]
org = "wso2healthcare"
name = "eob.api"
version = "0.2.3"
distribution = "2201.6.0"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare", "FHIR", "ExplanationOfBenefit", "r4", "international"]
template = true

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "2.0.1"
repository="local"

[[dependency]]
org = "ballerinax"
name = "health.fhirr4"
version = "2.0.1"
repository="local"
